### ISSUE TITLE
SEPM

### ISSUE THREAD

**Issue by ninhhv** [TrongTan124/ghi-chep-ELK-OPS#1]
Mình đang vướng chỗ parser log của Symantec Endpoint Protect, nếu có thể nhờ bạn giúp phần Grok cho log này

**Comment by TrongTan124** [comment]
Bạn gửi mẫu log và mong muốn tách như nào cho mình nhé.                                                                                                                                                                        Đã gửi thông qua BlackBerry Hub dành cho Android                                                                                                                                                                           Từ: notifications@github.comĐã gửi: Ngày 10 tháng 04 năm 2018 18:46Tới: ghi-chep-ELK-OPS@noreply.github.comTrả lời: reply@reply.github.comCc: subscribed@noreply.github.comChủ đề: [TrongTan124/ghi-chep-ELK-OPS] SEPM (#1)  Mình đang vướng chỗ parser log của Symantec Endpoint Protect, nếu có thể nhờ bạn giúp phần Grok cho log này

**Comment by ninhhv** [comment]
Mình cũng chưa biết phải xử lý như thế nào? nhưng mục tiêu là có agent forward logs từ SEPM tới Logstash, và logstash sẽ Grok cái logs đó rồi đẩy vào cho ElasticSearch.
